FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY files/kanban-issues-0.0.1-SNAPSHOT.jar /opt/lib/
COPY entrypoint-issues.sh /opt/bin/entrypoint-issues.sh
RUN chmod 755 /opt/bin/entrypoint-issues.sh
ENTRYPOINT ["/opt/bin/entrypoint-issues.sh"]
#CMD ["-jar", "/opt/lib/kanban-issues-0.0.1-SNAPSHOT.jar"]
EXPOSE 8081