FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY files/kanban-dashboards-0.0.1-SNAPSHOT.jar /opt/lib/
COPY entrypoint-dashboards.sh /opt/bin/entrypoint-dashboards.sh
RUN chmod 755 /opt/bin/entrypoint-dashboards.sh
#ENTRYPOINT ["/usr/bin/java"]
#CMD ["-jar", "/opt/lib/kanban-dashboards-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080